version: "3.9"
services:
  db:
    image: "mysql:8.0"
    container_name: clone-db
    ports:
      - "3365:3306"
    volumes:
      - ./store/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clone
    restart: no

  app:
    container_name: inflearn-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - env.docker
    restart: no