### DB ###
# Jpa
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PW}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=false

# hikari
spring.datasource.hikari.maximum-pool-size=50


### AWS ###
aws.access-key=${S3_ACCESS_KEY}
aws.secret-key=${S3_SECRET_KEY}
aws.s3.bucket=dev-bucket

### JWT ###
jwt.token.key=TEST_TOKEN


spring.profiles.group.local=local
spring.profiles.group.dev=dev

spring.application.name=inflearn
server.servlet.context-path=/api
server.port=8080

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr([%X{traceId}]){magenta} %clr(%-5level){INFO=green, WARN=yellow, ERROR=red} : %msg%n

#---
spring.config.activate.on-profile=local
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.type.descriptor.sql=trace
spring.sql.init.mode=always
#---
spring.config.activate.on-profile=dev
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.type.descriptor.sql=off
spring.sql.init.mode=never